FROM mrlindsay/fin_gamma:main


# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container
COPY . /app

# Specify the command to run the Python script
CMD ["python", "script.py"]